apiVersion: v1
kind: Service
metadata:
  name: {{ template "teleport.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      targetPort: 3080
      protocol: TCP
  selector:
    app: {{ template "teleport.name" . }}
    release: {{ .Release.Name }}
{{- end }}
